
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sphinx
      run: |
        python -m pip install sphinx
        python -m pip install breathe
        cd sphinx
        make html
    
    - name: Tests
      run: |
        cd tests/parser
        pytest
        cd ..
        cd data_pipeline
        cd feature_engineering
        pytest

    - name: Poetry
      run: |
        python -m pip install poetry
        poetry build
        poetry config pypi-token $PYPI_API_KEY
        poetry publish